# CI/CD pipeline service account with restricted cluster access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-cd-pipeline
  namespace: ci-cd
  annotations:
    kubernetes.io/service-account.expiration: "2024-12-31T23:59:59Z"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-cd-deployer
rules:
# Namespace management for environment provisioning
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "get", "list", "create", "update", "patch" ]
# Application deployment across allowed namespaces
- apiGroups: [ "apps" ]
  resources: [ "deployments", "replicasets", "daemonsets", "statefulsets" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
# Configuration and service management
- apiGroups: [ "" ]
  resources: [ "services", "configmaps", "secrets" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
# Ingress configuration for external access
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
# Cluster binding with namespace restrictions enforced by admission controllers
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-cd-binding
  annotations:
    allowed-namespaces: "development,staging,testing"
subjects:
- kind: ServiceAccount
  name: ci-cd-pipeline
  namespace: ci-cd
roleRef:
  kind: ClusterRole
  name: ci-cd-deployer
  apiGroup: rbac.authorization.k8s.io
